services:
  app:
    build: .
    env_file: .env.docker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_prod
    volumes:
      - static:/app/staticfiles
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/staticfiles
    depends_on:
      - app

volumes:
  static: